# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1ceded2feba688572441ff792e77e9fb107be811c2a83170bcf46a3e61aea24c5f966ff8dffa143f7430e2cf1d6db486ce3f8d673db4d2899906c8411d1f97

test:
  secret_key_base: 4c942380a4612cd2e1bb2ce6da8665291eb44017083f367d4cbd180750144ab5e10450a53451f66b5bd981f6752efcf361d06351bed09953ffd0bbd1c4a86898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
